# -*- coding: utf-8 -*-
"""homework2_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/PLACEHOLDER

# Homework 2: Policy Gradient vs Value-Based RL in JAX
"""

"""# Install Dependencies"""

# Uncomment and run once in Colab:
# !pip install gymnasium jax jaxlib optax matplotlib numpy pyyaml

"""# Environmental Setup"""

import os
import yaml
import json
import time
import random
import gc
import pickle
import numpy as np

BASE_DIR = os.getcwd()

if "__file__" in globals():
  BASE_DIR = os.path.dirname(os.path.abspath(__file__))

config_path = os.path.join(BASE_DIR, "config.yaml")

with open(config_path) as f:
  cfg = yaml.safe_load(f)

DIRS = {
  "logs":  os.path.join(BASE_DIR, "logs"),
  "ckpt":  os.path.join(BASE_DIR, "checkpoints"),
  "plots": os.path.join(BASE_DIR, "plots"),
}

for d in DIRS.values():
  os.makedirs(d, exist_ok=True)

print(f"Environment setup completed in {BASE_DIR}")

"""# Grid World Environment

Design rationale:
- 8x8 grid, start=(0,0), goal=(7,7)
- Three staggered obstacle rows create a structured maze that rewards
  long-horizon planning and exposes differences between DQN and REINFORCE.
- Stochastic transitions (noise=0.1): with 10% probability the intended
  action is replaced by a uniformly random one, modelling real-world
  actuation noise and testing robustness of both algorithms.
- Reward shaping: +1.0 goal, -0.01 per step, -0.5 obstacle hit (agent
  bounces back), -0.05 wall collision.  The sparse +1 reward makes
  credit assignment non-trivial and is the primary research question.
"""

import gymnasium as gym
from gymnasium import spaces

class GridWorldEnv(gym.Env):

  metadata = {"render_modes": ["ansi"]}

  # Action indices
  UP    = 0
  DOWN  = 1
  LEFT  = 2
  RIGHT = 3

  _DELTAS = {UP: (-1, 0), DOWN: (1, 0), LEFT: (0, -1), RIGHT: (0, 1)}

  def __init__(self, cfg_env, seed=None):
    super().__init__()

    self.grid_size       = cfg_env["grid_size"]
    self.max_steps       = cfg_env["max_steps"]
    self.noise           = cfg_env["noise"]
    self.obstacles       = set(map(tuple, cfg_env["obstacles"]))
    self.goal_reward     = cfg_env["goal_reward"]
    self.step_reward     = cfg_env["step_reward"]
    self.obstacle_reward = cfg_env["obstacle_reward"]
    self.wall_penalty    = cfg_env["wall_penalty"]

    n = self.grid_size
    self.start = (0, 0)
    self.goal  = (n - 1, n - 1)

    self.n_states  = n * n
    self.n_actions = 4

    self.observation_space = spaces.Discrete(self.n_states)
    self.action_space      = spaces.Discrete(self.n_actions)

    self._rng   = np.random.default_rng(seed)
    self._steps = 0
    self._pos   = self.start

  def _encode(self, pos):
    return pos[0] * self.grid_size + pos[1]

  def _clamp(self, pos):
    r, c = pos
    return (
      max(0, min(self.grid_size - 1, r)),
      max(0, min(self.grid_size - 1, c)),
    )

  def reset(self, seed=None, options=None):
    if seed is not None:
      self._rng = np.random.default_rng(seed)
    self._steps = 0
    self._pos   = self.start
    return self._encode(self._pos), {}

  def step(self, action):
    # Stochastic transition: replace action with random one with prob noise
    if self._rng.random() < self.noise:
      action = int(self._rng.integers(0, self.n_actions))

    dr, dc  = self._DELTAS[int(action)]
    new_pos = self._clamp((self._pos[0] + dr, self._pos[1] + dc))

    hit_wall     = (new_pos == self._pos)
    hit_obstacle = (new_pos in self.obstacles)

    if hit_obstacle:
      reward  = self.obstacle_reward
      new_pos = self._pos           # bounce back
    elif new_pos == self.goal:
      reward = self.goal_reward
    else:
      reward = self.step_reward

    if hit_wall and not hit_obstacle:
      reward += self.wall_penalty

    self._pos    = new_pos
    self._steps += 1

    terminated = (self._pos == self.goal)
    truncated  = (self._steps >= self.max_steps)

    return self._encode(self._pos), float(reward), terminated, truncated, {}

  def render(self, mode="ansi"):
    n    = self.grid_size
    grid = [["." for _ in range(n)] for _ in range(n)]
    for (r, c) in self.obstacles:
      grid[r][c] = "X"
    gr, gc = self.goal
    grid[gr][gc] = "G"
    ar, ac = self._pos
    grid[ar][ac] = "A"
    return "\n".join(" ".join(row) for row in grid)


def make_env(cfg_env, seed=None):
  return GridWorldEnv(cfg_env, seed=seed)


# Sanity check
_env = make_env(cfg["env"])
_obs, _ = _env.reset()
print(f"GridWorldEnv | {cfg['env']['grid_size']}x{cfg['env']['grid_size']} | "
      f"n_states={_env.n_states} | n_actions={_env.n_actions} | "
      f"obstacles={len(_env.obstacles)} | noise={cfg['env']['noise']}")
print(_env.render())
del _env

"""# Utilities

  * standardized seeds
  * one-hot encoding
  * cleanup
"""

def seed_everything(seed: int):
  random.seed(seed)
  np.random.seed(seed)


def one_hot(state: int, n_states: int) -> np.ndarray:
  v = np.zeros(n_states, dtype=np.float32)
  v[state] = 1.0
  return v


def cleanup():
  gc.collect()
  print("Cleanup Done")

"""# JAX / Neural Network Utilities"""

import jax
import jax.numpy as jnp
from jax import jit, vmap, value_and_grad
import optax


def random_layer_params(m, n, key, scale=1e-2):
  w_key, b_key = jax.random.split(key)
  return (
    scale * jax.random.normal(w_key, (n, m)),
    scale * jax.random.normal(b_key, (n,)),
  )


def init_mlp_params(sizes, key):
  keys = jax.random.split(key, len(sizes) - 1)
  return [
    random_layer_params(m, n, k)
    for m, n, k in zip(sizes[:-1], sizes[1:], keys)
  ]


def relu(x):
  return jnp.maximum(0.0, x)


def mlp_forward(params, x):
  """Single-sample MLP forward pass.  Returns raw logits."""
  activations = x
  for w, b in params[:-1]:
    activations = relu(jnp.dot(w, activations) + b)
  w, b = params[-1]
  return jnp.dot(w, activations) + b


batched_mlp_forward = vmap(mlp_forward, in_axes=(None, 0))

"""# Replay Buffer"""

class ReplayBuffer:
  """Fixed-capacity circular replay buffer backed by numpy arrays."""

  def __init__(self, capacity, state_dim):
    self.capacity  = capacity
    self.state_dim = state_dim
    self._ptr      = 0
    self._size     = 0

    self.states      = np.zeros((capacity, state_dim), dtype=np.float32)
    self.actions     = np.zeros(capacity,              dtype=np.int32)
    self.rewards     = np.zeros(capacity,              dtype=np.float32)
    self.next_states = np.zeros((capacity, state_dim), dtype=np.float32)
    self.dones       = np.zeros(capacity,              dtype=np.float32)

  def push(self, state, action, reward, next_state, done):
    idx = self._ptr % self.capacity
    self.states[idx]      = state
    self.actions[idx]     = action
    self.rewards[idx]     = reward
    self.next_states[idx] = next_state
    self.dones[idx]       = float(done)
    self._ptr  = (self._ptr + 1) % self.capacity
    self._size = min(self._size + 1, self.capacity)

  def sample(self, batch_size, rng):
    idxs = rng.integers(0, self._size, size=batch_size)
    return (
      jax.device_put(self.states[idxs]),
      jax.device_put(self.actions[idxs]),
      jax.device_put(self.rewards[idxs]),
      jax.device_put(self.next_states[idxs]),
      jax.device_put(self.dones[idxs]),
    )

  def __len__(self):
    return self._size

"""# DQN Agent (JAX)

Uses a Q-network (MLP) with experience replay and a periodically synced
target network.  The update step is jit-compiled; the optimizer and gamma
are captured in the closure so that one compiled binary is shared across
all training steps within a single (lr, gamma) experiment.
"""

def make_dqn_update_fn(optimizer, gamma):
  """
  Factory: builds and returns a jit-compiled DQN update step.
  Closing over `optimizer` and `gamma` means JAX traces once per
  unique (lr, gamma) combination - acceptable for a hyperparameter sweep.
  """

  def loss_fn(params, target_params, states, actions, rewards, next_states, dones):
    q_vals  = batched_mlp_forward(params, states)                  # (B, A)
    q_next  = batched_mlp_forward(target_params, next_states)      # (B, A)
    # Bellman target - stop_gradient prevents gradients through target network
    q_tgt   = rewards + gamma * jnp.max(q_next, axis=1) * (1.0 - dones)
    q_tgt   = jax.lax.stop_gradient(q_tgt)                        # (B,)
    B       = states.shape[0]
    q_pred  = q_vals[jnp.arange(B), actions]                      # (B,)
    return jnp.mean((q_pred - q_tgt) ** 2)

  @jit
  def update_step(params, opt_state, target_params,
                  states, actions, rewards, next_states, dones):
    loss, grads = value_and_grad(loss_fn)(
      params, target_params, states, actions, rewards, next_states, dones
    )
    updates, new_opt_state = optimizer.update(grads, opt_state)
    new_params = optax.apply_updates(params, updates)
    return new_params, new_opt_state, loss

  return update_step


def run_dqn_experiment(seed, lr, gamma, cfg):
  print(f"--- DQN | lr={lr} | gamma={gamma} | seed={seed} ---")

  n_states   = cfg["env"]["grid_size"] ** 2
  n_actions  = 4
  hidden_dim = cfg["dqn"]["hidden_dim"]

  key           = jax.random.PRNGKey(seed)
  params        = init_mlp_params([n_states, hidden_dim, n_actions], key)
  target_params = jax.tree.map(jnp.array, params)   # deep copy

  optimizer  = optax.adam(lr)
  opt_state  = optimizer.init(params)
  update_fn  = make_dqn_update_fn(optimizer, gamma)

  buffer     = ReplayBuffer(cfg["dqn"]["buffer_size"], n_states)
  rng        = np.random.default_rng(seed)
  env        = make_env(cfg["env"], seed=seed)

  eps          = cfg["dqn"]["epsilon_start"]
  eps_end      = cfg["dqn"]["epsilon_end"]
  eps_decay    = cfg["dqn"]["epsilon_decay"]
  batch_size   = cfg["dqn"]["batch_size"]
  tgt_freq     = cfg["dqn"]["target_update_freq"]

  episode_rewards = []
  global_step     = 0

  for ep in range(cfg["training"]["num_episodes"]):
    obs, _    = env.reset(seed=int(seed + ep))
    ep_reward = 0.0
    done      = False

    while not done:
      sv = one_hot(obs, n_states)

      # Epsilon-greedy action selection
      if rng.random() < eps:
        action = int(rng.integers(0, n_actions))
      else:
        q_vals = mlp_forward(params, jax.device_put(sv))
        action = int(jnp.argmax(q_vals))

      next_obs, reward, terminated, truncated, _ = env.step(action)
      done = terminated or truncated

      buffer.push(sv, action, reward, one_hot(next_obs, n_states), float(done))
      obs         = next_obs
      ep_reward  += reward
      global_step += 1

      if len(buffer) >= batch_size:
        s, a, r, ns, d = buffer.sample(batch_size, rng)
        params, opt_state, _ = update_fn(
          params, opt_state, target_params, s, a, r, ns, d
        )

      # Hard target network sync
      if global_step % tgt_freq == 0:
        target_params = jax.tree.map(jnp.array, params)

    eps = max(eps_end, eps * eps_decay)
    episode_rewards.append(float(ep_reward))

  env.close()
  return episode_rewards, params

"""# REINFORCE Agent (JAX)

On-policy Monte Carlo policy gradient.  Collects a full episode,
computes normalised discounted returns, then updates the policy network
with a single jit-compiled gradient step.
"""

def make_reinforce_update_fn(optimizer):
  """Factory: builds and returns a jit-compiled REINFORCE update step."""

  def loss_fn(params, states, actions, returns):
    logits    = batched_mlp_forward(params, states)                # (T, A)
    log_probs = logits - jax.nn.logsumexp(logits, axis=1, keepdims=True)  # log-softmax
    T         = states.shape[0]
    lp_taken  = log_probs[jnp.arange(T), actions]                 # (T,)
    return -jnp.mean(returns * lp_taken)

  @jit
  def update_step(params, opt_state, states, actions, returns):
    loss, grads = value_and_grad(loss_fn)(params, states, actions, returns)
    updates, new_opt_state = optimizer.update(grads, opt_state)
    new_params = optax.apply_updates(params, updates)
    return new_params, new_opt_state, loss

  return update_step


def compute_returns(rewards, gamma):
  """Discounted returns G_t, normalised to zero mean / unit variance."""
  T       = len(rewards)
  returns = np.zeros(T, dtype=np.float32)
  G       = 0.0
  for t in reversed(range(T)):
    G          = rewards[t] + gamma * G
    returns[t] = G
  std = returns.std()
  if std > 1e-8:
    returns = (returns - returns.mean()) / std
  return returns


def run_reinforce_experiment(seed, lr, gamma, cfg):
  print(f"--- REINFORCE | lr={lr} | gamma={gamma} | seed={seed} ---")

  n_states   = cfg["env"]["grid_size"] ** 2
  n_actions  = 4
  hidden_dim = cfg["reinforce"]["hidden_dim"]

  key       = jax.random.PRNGKey(seed)
  params    = init_mlp_params([n_states, hidden_dim, n_actions], key)

  optimizer = optax.adam(lr)
  opt_state = optimizer.init(params)
  update_fn = make_reinforce_update_fn(optimizer)

  rng = np.random.default_rng(seed)
  env = make_env(cfg["env"], seed=seed)

  episode_rewards = []

  for ep in range(cfg["training"]["num_episodes"]):
    obs, _ = env.reset(seed=int(seed + ep))

    ep_states  = []
    ep_actions = []
    ep_rewards = []
    done       = False

    while not done:
      sv      = jax.device_put(one_hot(obs, n_states))
      logits  = mlp_forward(params, sv)
      probs   = np.array(jnp.exp(logits - jax.nn.logsumexp(logits)), dtype=np.float64)
      probs  /= probs.sum()                          # renormalise for numerical safety
      action  = int(rng.choice(n_actions, p=probs))

      next_obs, reward, terminated, truncated, _ = env.step(action)
      done = terminated or truncated

      ep_states.append(one_hot(obs, n_states))
      ep_actions.append(action)
      ep_rewards.append(reward)
      obs = next_obs

    returns = compute_returns(ep_rewards, gamma)

    states_jax  = jax.device_put(np.array(ep_states,  dtype=np.float32))
    actions_jax = jax.device_put(np.array(ep_actions, dtype=np.int32))
    returns_jax = jax.device_put(returns)

    params, opt_state, _ = update_fn(
      params, opt_state, states_jax, actions_jax, returns_jax
    )

    episode_rewards.append(float(sum(ep_rewards)))

  env.close()
  return episode_rewards, params

"""# Random Baseline"""

def run_random_experiment(seed, cfg):
  print(f"--- Random | seed={seed} ---")

  rng = np.random.default_rng(seed)
  env = make_env(cfg["env"], seed=seed)

  episode_rewards = []

  for ep in range(cfg["training"]["num_episodes"]):
    obs, _ = env.reset(seed=int(seed + ep))
    ep_reward = 0.0
    done      = False

    while not done:
      action     = int(rng.integers(0, env.n_actions))
      obs, r, terminated, truncated, _ = env.step(action)
      done       = terminated or truncated
      ep_reward += r

    episode_rewards.append(float(ep_reward))

  env.close()
  return episode_rewards

"""# Experiment Runner"""

def run_all_experiments(cfg):
  lrs    = cfg["hyperparameters"]["learning_rates"]
  gammas = cfg["hyperparameters"]["discount_factors"]
  seeds  = [cfg["seed_base"] + i for i in range(cfg["num_seeds"])]

  results = {"random": {}, "dqn": {}, "reinforce": {}}

  # ── Random Baseline ──────────────────────────────────────────
  print("=" * 60)
  print("Running Random Baseline")
  print("=" * 60)
  results["random"]["default"] = []
  for seed in seeds:
    rewards = run_random_experiment(seed, cfg)
    results["random"]["default"].append({"seed": seed, "episode_rewards": rewards})
    print(f"  seed={seed} | mean_reward={np.mean(rewards):.4f}")

  # ── DQN ──────────────────────────────────────────────────────
  for lr in lrs:
    for gamma in gammas:
      hp_key = f"lr{lr}_gamma{gamma}"
      print("=" * 60)
      print(f"Running DQN | lr={lr} | gamma={gamma}")
      print("=" * 60)
      results["dqn"][hp_key] = []

      for seed in seeds:
        t0 = time.time()
        rewards, params = run_dqn_experiment(seed, lr, gamma, cfg)
        elapsed = time.time() - t0

        results["dqn"][hp_key].append({
          "seed": seed, "lr": lr, "gamma": gamma,
          "episode_rewards": rewards, "elapsed_s": round(elapsed, 2),
        })

        ckpt_path = os.path.join(DIRS["ckpt"], f"dqn_{hp_key}_seed{seed}.pkl")
        with open(ckpt_path, "wb") as f:
          pickle.dump(params, f)

        print(f"  seed={seed} | mean_reward={np.mean(rewards):.4f} | time={elapsed:.1f}s")

  # ── REINFORCE ────────────────────────────────────────────────
  for lr in lrs:
    for gamma in gammas:
      hp_key = f"lr{lr}_gamma{gamma}"
      print("=" * 60)
      print(f"Running REINFORCE | lr={lr} | gamma={gamma}")
      print("=" * 60)
      results["reinforce"][hp_key] = []

      for seed in seeds:
        t0 = time.time()
        rewards, params = run_reinforce_experiment(seed, lr, gamma, cfg)
        elapsed = time.time() - t0

        results["reinforce"][hp_key].append({
          "seed": seed, "lr": lr, "gamma": gamma,
          "episode_rewards": rewards, "elapsed_s": round(elapsed, 2),
        })

        ckpt_path = os.path.join(DIRS["ckpt"], f"reinforce_{hp_key}_seed{seed}.pkl")
        with open(ckpt_path, "wb") as f:
          pickle.dump(params, f)

        print(f"  seed={seed} | mean_reward={np.mean(rewards):.4f} | time={elapsed:.1f}s")

  return results


"""## Execution Loop"""

results = run_all_experiments(cfg)
cleanup()

"""## Save Logs"""

log_path = os.path.join(DIRS["logs"], "results.json")
with open(log_path, "w") as f:
  json.dump(results, f, indent=2)

print(f"All results saved → {log_path}")

"""# Plotting - Learning Curves"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm

# ── Helpers ──────────────────────────────────────────────────

def get_runs(results, agent, key):
  return [r["episode_rewards"] for r in results[agent][key]]


def mean_and_se(runs):
  min_len = min(len(r) for r in runs)
  arr  = np.array([r[:min_len] for r in runs])
  mean = arr.mean(axis=0)
  se   = arr.std(axis=0) / np.sqrt(len(runs))
  xs   = np.arange(min_len)
  return mean, se, xs


def get_best_key(results, agent):
  """Key with highest mean reward over the final 50 episodes."""
  best_key, best_val = None, -np.inf
  for key in results[agent]:
    runs  = get_runs(results, agent, key)
    score = np.mean([np.mean(r[-50:]) for r in runs])
    if score > best_val:
      best_val = score
      best_key = key
  return best_key


COLORS = {"random": "#888888", "dqn": "#1976D2", "reinforce": "#E64A19"}

# ── Plot 1: Mean ± Standard Error (best config per algorithm) ─

fig, ax = plt.subplots(figsize=(10, 5))

mean, se, xs = mean_and_se(get_runs(results, "random", "default"))
ax.plot(xs, mean, label="Random", color=COLORS["random"])
ax.fill_between(xs, mean - se, mean + se, alpha=0.2, color=COLORS["random"])

for agent in ["dqn", "reinforce"]:
  bk           = get_best_key(results, agent)
  mean, se, xs = mean_and_se(get_runs(results, agent, bk))
  ax.plot(xs, mean, label=f"{agent.upper()} (best: {bk})", color=COLORS[agent])
  ax.fill_between(xs, mean - se, mean + se, alpha=0.2, color=COLORS[agent])

ax.set_xlabel("Episode")
ax.set_ylabel("Episode Reward")
ax.set_title("Mean ± Standard Error | Best Config per Algorithm | 10 Seeds")
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
p = os.path.join(DIRS["plots"], "plot1_mean_se.png")
plt.savefig(p, dpi=150, bbox_inches="tight")
plt.show()
print(f"Saved: {p}")

# ── Plot 2: All 10 Individual Seed Runs ───────────────────────

for agent in ["dqn", "reinforce"]:
  bk      = get_best_key(results, agent)
  runs    = get_runs(results, agent, bk)
  min_len = min(len(r) for r in runs)
  cmap    = cm.get_cmap("tab10", len(runs))

  fig, ax = plt.subplots(figsize=(10, 5))
  for i, run in enumerate(runs):
    seed = results[agent][bk][i]["seed"]
    ax.plot(run[:min_len], color=cmap(i), alpha=0.75, label=f"seed {seed}")

  ax.set_xlabel("Episode")
  ax.set_ylabel("Episode Reward")
  ax.set_title(f"{agent.upper()} — All 10 Individual Runs | {bk}")
  ax.legend(fontsize=7, ncol=2)
  ax.grid(True, alpha=0.3)
  plt.tight_layout()
  p = os.path.join(DIRS["plots"], f"plot2_individual_{agent}.png")
  plt.savefig(p, dpi=150, bbox_inches="tight")
  plt.show()
  print(f"Saved: {p}")

# ── Plot 3: Hyperparameter Sensitivity ────────────────────────

lrs    = cfg["hyperparameters"]["learning_rates"]
gammas = cfg["hyperparameters"]["discount_factors"]
ls_map = {0.9: "-", 0.99: "--"}

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, agent in zip(axes, ["dqn", "reinforce"]):
  for gamma in gammas:
    for lr in lrs:
      key         = f"lr{lr}_gamma{gamma}"
      mean, _, xs = mean_and_se(get_runs(results, agent, key))
      ax.plot(xs, mean, linestyle=ls_map.get(gamma, "-"),
              label=f"lr={lr}, γ={gamma}", alpha=0.85)
  ax.set_title(f"{agent.upper()} — Hyperparameter Sensitivity")
  ax.set_xlabel("Episode")
  ax.set_ylabel("Mean Episode Reward")
  ax.legend(fontsize=7)
  ax.grid(True, alpha=0.3)

plt.tight_layout()
p = os.path.join(DIRS["plots"], "plot3_hyperparam_sensitivity.png")
plt.savefig(p, dpi=150, bbox_inches="tight")
plt.show()
print(f"Saved: {p}")

"""# Policy Visualization

Arrow directions map directly to the agent's greedy action in each cell.
A visit-count heatmap (generated by running the greedy policy for 1000
steps) is overlaid to show where the agent spends most of its time.
"""

# Action -> (col_offset, row_offset) in imshow coordinates
# imshow origin="upper": row 0 at top, y increases downward.
# UP (-row) => dy=-0.35   DOWN (+row) => dy=+0.35
# LEFT (-col) => dx=-0.35  RIGHT (+col) => dx=+0.35
_ACTION_DX = {0:  0.00, 1:  0.00, 2: -0.35, 3:  0.35}
_ACTION_DY = {0: -0.35, 1:  0.35, 2:  0.00, 3:  0.00}


def greedy_policy_grid(params, n_states, grid_size):
  """Return (grid_size, grid_size) array of greedy actions."""
  policy = np.zeros((grid_size, grid_size), dtype=int)
  for s in range(n_states):
    sv = jax.device_put(one_hot(s, n_states))
    policy[s // grid_size, s % grid_size] = int(jnp.argmax(mlp_forward(params, sv)))
  return policy


def plot_policy_heatmap(params, agent, hp_key, cfg_env, seed):
  grid_size = cfg_env["grid_size"]
  obstacles = set(map(tuple, cfg_env["obstacles"]))
  goal      = (grid_size - 1, grid_size - 1)
  n_states  = grid_size ** 2

  policy    = greedy_policy_grid(params, n_states, grid_size)

  # Build visit-count map via greedy policy rollout
  visit_map = np.zeros((grid_size, grid_size), dtype=float)
  env       = make_env(cfg_env, seed=seed)
  obs, _    = env.reset(seed=seed)
  for _ in range(cfg_env["max_steps"] * 5):
    r, c = divmod(obs, grid_size)
    visit_map[r, c] += 1
    obs, _, terminated, truncated, _ = env.step(int(policy[r, c]))
    if terminated or truncated:
      obs, _ = env.reset(seed=seed)
  env.close()

  fig, ax = plt.subplots(figsize=(7, 7))
  im = ax.imshow(visit_map, cmap="YlOrRd", origin="upper", interpolation="nearest")
  plt.colorbar(im, ax=ax, label="Visit count (greedy rollout)")

  for r in range(grid_size):
    for c in range(grid_size):
      if (r, c) in obstacles:
        ax.add_patch(plt.Rectangle(
          (c - 0.5, r - 0.5), 1, 1, color="black", zorder=2
        ))
      elif (r, c) == goal:
        ax.add_patch(plt.Rectangle(
          (c - 0.5, r - 0.5), 1, 1, color="#4CAF50", alpha=0.6, zorder=2
        ))
        ax.text(c, r, "G", ha="center", va="center",
                fontsize=13, fontweight="bold", color="white", zorder=3)
      else:
        a  = int(policy[r, c])
        dx = _ACTION_DX[a]
        dy = _ACTION_DY[a]
        ax.annotate("", xy=(c + dx, r + dy), xytext=(c, r),
                    arrowprops=dict(arrowstyle="->", color="steelblue",
                                   lw=1.5, mutation_scale=12),
                    zorder=3)

  # Mark start cell
  ax.scatter([0], [0], marker="*", s=250, color="gold", zorder=4, label="Start")

  ax.set_xlim(-0.5, grid_size - 0.5)
  ax.set_ylim(grid_size - 0.5, -0.5)   # keep row 0 at top
  ax.set_xticks(range(grid_size))
  ax.set_yticks(range(grid_size))
  ax.set_title(f"{agent.upper()} Greedy Policy | {hp_key} | seed={seed}")
  ax.legend(loc="lower right")
  plt.tight_layout()

  p = os.path.join(DIRS["plots"], f"policy_{agent}_{hp_key}_seed{seed}.png")
  plt.savefig(p, dpi=150, bbox_inches="tight")
  plt.show()
  print(f"Saved: {p}")


"""## Generate Policy Plots"""

for agent in ["dqn", "reinforce"]:
  bk      = get_best_key(results, agent)
  seed    = cfg["seed_base"]
  ckpt    = os.path.join(DIRS["ckpt"], f"{agent}_{bk}_seed{seed}.pkl")
  with open(ckpt, "rb") as f:
    params = pickle.load(f)
  plot_policy_heatmap(params, agent, bk, cfg["env"], seed)

print("All experiments and plots complete.")
